version: "3.7"

services:
  worker:
    build: ./Worker
  client:
    build: ./Client
    depends_on:
      - worker
  seq:
    logging:
      driver: none
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment: 
      - ACCEPT_EULA=Y
  consul:
    logging:
      driver: none
    image: bitnami/consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'