version: "3.7"

services:
  alpha:
    build: ./Worker
    environment:
      - Proto_Hostname=alpha
    depends_on:
      - consul
      - seq
  beta:
    build: ./Worker
    environment:
      - Proto_Hostname=beta
    depends_on:
      - consul
      - seq
  gamma:
    build: ./Worker
    environment:
      - Proto_Hostname=gamma
    depends_on:
      - consul
      - seq
  delta:
    build: ./Worker
    environment:
      - Proto_Hostname=delta
    depends_on:
      - consul
      - seq
  epsilon:
    build: ./Worker
    environment:
      - Proto_Hostname=epsilon
    depends_on:
      - consul
      - seq
  client:
    build: ./Client
    depends_on:
      - consul
      - alpha
      - beta
      - gamma
      - delta
      - epsilon
  seq:
    logging:
      driver: none
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment: 
      - ACCEPT_EULA=Y
  consul:
    logging:
      driver: none
    image: bitnami/consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'