name: Build and deploy

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'

      - name: Build
        run: dotnet build -c Release

      - name: Run tests
        run: |
          dotnet test -c Release
        
  nuget:
    runs-on: windows-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v1

    - name: Create and push NuGet package
      run: |
        dotnet pack -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
  